#!/usr/bin/env bash

if [[ "${BASH_SOURCE[0]}" = "${0}" ]] && [[ "$1" = "--forever" ]]; then
    path="/usr/local/lib/python3.5/dist-packages"
    PYTHONPATH="$path:$PYTHONPATH"
    echo "PYTHONPATH=$PYTHONPATH" >> ~/.bashrc
    echo "Added $PYTHONPATH export to .bashrc"
elif [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    path="/usr/local/lib/python3.5/dist-packages"
    PYTHONPATH="$path:$PYTHONPATH"
else
    echo "You need to either source the $0 or run it with --forever option to add the path to bashrc"
fi
